version: '3.8'

services:
  postgres:
    image: postgres:14-alpine3.15
    network_mode: bridge
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
  app:
    image: nestjs-api-prod:1.0.0
    network_mode: bridge
    build:
      context: .
      target: production
      dockerfile: ./Dockerfile
    command: npx prisma migrate deploy && npm run prod
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      DATABASE_URL: postgresql://postgres:${DB_PASSWORD}@postgres:5432/postgres
      SECRET: ${SECRET}
      CDN_SPACE: galliary-images
      CDN_REGION: nyc3
      CDN_ENDPOINT: nyc3.digitaloceanspaces.com
      CDN_URL: https://cdn.galliary.com
      CDN_API_KEY: ${CDN_API_KEY}
      CDN_API_SECRET: ${CDN_API_SECRET}
    restart: unless-stopped

volumes:
  postgres: ~